/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function unit_test_Shaders_02(props) {
  const { nodes, materials } = useGLTF("unitTests/unit_test_Shaders_02.gltf");

  console.log("unit_test_Shaders_02: nodes", nodes);
  console.log("unit_test_Shaders_02: materials", materials);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder1.geometry}
        material={materials.Bricks03}
        position={[0, 1, 0]}
        scale={[0.5, 1, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials.asphalt_white_stripe}
        scale={10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials.Painted_metal_01}
        position={[1.26, 2.37, 0.03]}
        scale={0.37}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder2.geometry}
        material={materials.Asphalt08}
        position={[1.27, 1, 0]}
        scale={[0.5, 1, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Suzanne.geometry}
        material={materials["PaintedMetal02.001"]}
        position={[0, 1.55, -0.01]}
        rotation={[-0.62, 0, 0]}
        scale={0.42}
      />
    </group>
  );
}

